# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

# this needs more testing if we can have frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# Configuration parameters: AllowKeywordBlockArguments.
Lint/UnderscorePrefixedVariableName:
  Exclude:
    - 'src/include/proxy/dialogs.rb'

# Offense count: 7
Metrics/AbcSize:
  Max: 255

# Offense count: 5
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 150

# Offense count: 12
# Configuration parameters: CountBlocks.
Metrics/BlockNesting:
  Max: 5

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 355

# Offense count: 8
Metrics/CyclomaticComplexity:
  Max: 60

# Offense count: 10
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 320

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 600

# Offense count: 7
Metrics/PerceivedComplexity:
  Max: 62

# Offense count: 1
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, AllowedAcronyms.
# AllowedAcronyms: CLI, DSL, ACL, API, ASCII, CPU, CSS, DNS, EOF, GUID, HTML, HTTP, HTTPS, ID, IP, JSON, LHS, QPS, RAM, RHS, RPC, SLA, SMTP, SQL, SSH, TCP, TLS, TTL, UDP, UI, UID, UUID, URI, URL, UTF8, VM, XML, XMPP, XSRF, XSS
Naming/FileName:
  Exclude:
    - 'src/modules/Proxy.rb'

# Offense count: 2
# Configuration parameters: MinNameLength, AllowNamesEndingInNumbers, AllowedNames, ForbiddenNames.
# AllowedNames: io, id, to, by, on, in, at, ip, db
Naming/MethodParameterName:
  Exclude:
    - 'src/modules/Proxy.rb'

# Offense count: 6
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Exclude:
    - 'src/include/proxy/dialogs.rb'

Naming/MethodName:
  Enabled: false

# Offense count: 4
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'src/include/proxy/dialogs.rb'
    - 'src/lib/proxy/auto_client.rb'
    - 'src/lib/proxy/client.rb'
    - 'src/modules/Proxy.rb'


